### ISSUE TITLE
CI3-beta: Hardcoded English texts.

### ISSUE THREAD

**Issue by ivantcholakov** [donjakobo/A3M#106]
ci3-beta/application/controllers/account/Forgot_password.php

The callback validation rule check_username_or_email() contains the texts 'Invalid e-mail address format' and 'Invalid username format' that are not covered by the translation system.

Offtopic:

The method check_username_or_email() can be can be renamed into _check_username_or_email(), so it not be exposed to the browser. The corresponding callback rule then would have the name 'callback__check_username_or_email'.

**Comment by AdwinTrave** [comment]
I think I got them all by now, but I'll leave this open for a little bit more longer just in case.
