### ISSUE TITLE
php (5.3.27) fatal error with ci3-beta fresh install 

### ISSUE THREAD

**Issue by eakbas** [donjakobo/A3M#109]
I get the following error with a fresh ci3-beta install: 

Fatal error: require_once() [function.require]: Failed opening required '/home/.../system/libraries/Session/SessionHandlerInterface.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/.../system/libraries/Session/Session.php on line 122

it is true that the file '/home/.../system/libraries/Session/SessionHandlerInterface.php' is missing.

Upon further investigation, I noticed that SessionHandlerInterface is only available for PHP version>=5.4 and my version is 5.3.27. So, I suppose that this fatal error is related to the PHP version I use?

**Comment by portapipe** [comment]
I have the same "Class 'Hybrid_Logger' not found" issue in line 202.
Any news about the fix?

**Comment by AdwinTrave** [comment]
I'm currently in the process of updating everything to the latest development version of CI3 since they finally finished the new sessions. I do remember that there was some related bug to PHP 5.3.27 that was fixed, so we'll see if that fixes the issue.
My apologies on my inactivity. School is keeping me more busy then I would like to.

**Comment by AdwinTrave** [comment]
Check things now after #116

**Comment by rustyn** [comment]
I too am receiving the following error: `PHP Fatal error:  Class 'Hybrid_Logger' not found in /var/www/application/third_party/Hybrid/Endpoint.php on line 202`

This is with the most current CI3 branch install

**Comment by dima613** [comment]
I have exactly the same error too. :(
 yep, latest A3M 2 beta install

**Comment by AdwinTrave** [comment]
Looks like an issue with HybridAuth. Are you receiving this straight out of the box or after you try to use social login?

**Comment by rustyn** [comment]
This is when attempting social login, normal login and usage is perfectly fine. When attempting either FB or Twitter login/register it hits a blank page 500 error and my error_log shows the above error message.

**Comment by dima613** [comment]
Same here, any social login with Google FB or Twitter. Same error as rustyn

**Comment by j05u3** [comment]
check this: http://stackoverflow.com/questions/26795216/fatal-error-class-hybrid-logger-not-found-in-hybridauth-hybrid-endpoint-php/28789605#28789605

**Comment by charlesmudy** [comment]
Any update on this issue?

**Comment by AdwinTrave** [comment]
I just pushed some new stuff in regards to Hybrid Auth. I will be merging them soon.

**Comment by AdwinTrave** [comment]
I just pushed some new stuff in regards to Hybrid Auth. I will be merging them soon.

**Comment by charlesmudy** [comment]
Thanks for the update, I did a quick test and I keep getting `The page you requested was not found.` for Facebook, Twitter, Google. Any clue?

**Comment by AdwinTrave** [comment]
That is strange. I don't know, walk me through what you are doing and maybe I will be able to replicate the error myself. Did you setup the app settings properly (that is a common problem I used to have)?

**Comment by charlesmudy** [comment]
I almost felt the same but I don't think so because I did the same for the preview test that got me the same error as above.

* Downloaded the latest version
* Updated the database setting
* Updated my config base_url using something like www.test.dev
* Updated the /account/account.php social media to true and the keys
* Even updated a new version of the SQL

Missed something?

**Comment by AdwinTrave** [comment]
Works fine for me.
Anything in the logs?

**Comment by AdwinTrave** [comment]
Since PHP 5.3 is EOL I'm closing this issue.
