### ISSUE TITLE
Facebook profile picture not appearing on Manage Profile

### ISSUE THREAD

**Issue by grafxflow** [donjakobo/A3M#114]
By default when viewing the Facebook profile picture on the Manage Profile page it isn't appearing.

It seems that the <strong>?type=large?width=100&height=100</strong> doesn't work so it just needs to be <strong>?type=large</strong>.

I have noted out line 41 on <strong>/helpers/photo_helper.php</strong>
<code>// $path .= '?width='.$width.'&amp;height='.$height; // this appends size requirements to facebook image</code>

Is there anyway to disable this when calling the function <code><?php echo showPhoto(); ?></code> like the height and width are not required?

**Comment by donjakobo** [comment]
This sounds like a 1.X branch for CI 2.X.  Closing this as its old, will address this in CI3
