### ISSUE TITLE
New Facebook API, getting friends lists and email

### ISSUE THREAD

**Issue by calbertuk** [donjakobo/A3M#115]
Has anyone done this with A3M?

I've been trying to make a few changes and reading the Fb doc but I'm not competent enough to make the changes myself.

Has anybody integrated the new facebook API with A3M or made it possible to retrieve user_friends and the user email?

I'll be happy to pay someone to do it if it's not been done before.

**Comment by immodor** [comment]
Hi,
I have a problem with Sign up from social account does not work
Fatal error: Class 'Hybrid_Logger' not found in *****\a3m_ci3rc\application\third_party\Hybrid\Endpoint.php on line 202

**Comment by AdwinTrave** [comment]
Hello, please check the newest pull request. I think it might fix the issue.

**Comment by immodor** [comment]
yes, now it work
Thanks
