### ISSUE TITLE
404 Error on Social Accounts

### ISSUE THREAD

**Issue by maridansoft** [donjakobo/A3M#128]
When We try to go into social account login after activation in /account/account.php 

we get 404 error. 

I have tried to 

 */
    function provider_enabled($provider)
    {
		phpinfo();
		
		print_r($this->setup);
		die();
        return isset($this->setup['providers'][$provider]) && $this->setup['providers'][$provider]['enabled'];
    }

in hybrid_auth lib in /libraries folder, and it seems assignment of array is not happening fully and from the config file only the $config['third_party_auth'] = array(
// set on "base_url" the relative url that point to HybridAuth Endpoint
'base_url' => '/account/connect_end/',

The base URL part is taken, and the part 

"providers" => 

is totally ignored. 

How we can overcome this issue?

Best regards

**Comment by samuelsh** [comment]
@maridansoft 
Hi, I had the same issue.
Following changes in config.php fixed it:

$autoload['packages'] = array(APPPATH.'third_party/Hybrid');
...
$autoload['config'] = array("account/account.php");

**Comment by maridansoft** [comment]
Still 
An uncaught Exception was encountered

Type: Exception

Message: Authentication failed! Twitter returned an error. 401 Unauthorized.

Filename: /var/www/admin/data/www/offerhub.ovh/application/third_party/Hybrid/Auth.php

Line Number: 158

Backtrace:

File: /var/www/admin/data/www/offerhub.ovh/application/third_party/Hybrid/Auth.php
Line: 41
Function: initialize

File: /var/www/admin/data/www/offerhub.ovh/application/libraries/account/Hybrid_auth_lib.php
Line: 40
Function: __construct

File: /var/www/admin/data/www/offerhub.ovh/application/controllers/account/Connect_end.php
Line: 22
Function: __construct

File: /var/www/admin/data/www/offerhub.ovh/index.php
Line: 292
Function: require_once

**Comment by maridansoft** [comment]
It seems a twitter server time issue, which I cant figure out how to fix :(

**Comment by AdwinTrave** [comment]
There was a fix for Twitter recently in HybridAuth, will be included in the next pull. If that doesn't solve the issue then we'll have to look again.

**Comment by maridansoft** [comment]
would it be also in 3rd beta?

**Comment by AdwinTrave** [comment]
Eventually. Tonight I'm releasing new version of HybridAuth and if time permits it will be there tonight.

**Comment by maridansoft** [comment]
You rock man!

**Comment by maridansoft** [comment]
@AdwinTrave  still after fresh install the 404 thing is still there.

**Comment by AdwinTrave** [comment]
Back from the hell of finals. I will be looking into this in the coming weeks.

**Comment by maridansoft** [comment]
any news on this?

**Comment by AdwinTrave** [comment]
Looking at the code it looks like that the library thinks that the given provider is not enabled.

**Comment by AdwinTrave** [comment]
OK, found the issue and fixed it!
