### ISSUE TITLE
Exception not found

### ISSUE THREAD

**Issue by maridansoft** [donjakobo/A3M#135]
Fatal error: Class 'Hybrid_Exception' not found in 

/application/third_party/Hybrid/Endpoint.php on line 213
A PHP Error was encountered

Severity: Error

Message: Class 'Hybrid_Exception' not found

Filename: Hybrid/Endpoint.php

Line Number: 213

Backtrace

**Comment by AdwinTrave** [comment]
Hi, can you give me more information? Like what were you trying to do, so that I can try to replicate the issue.
Thanks!

**Comment by maridansoft** [comment]
trying to  authorize via facebook or twitter , i dont remember..

**Comment by AdwinTrave** [comment]
This is an error in HybridAuth. Try the newest version it might be fixed or not.
