### ISSUE TITLE
Permission Keys???

### ISSUE THREAD

**Issue by maridansoft** [donjakobo/A3M#136]
Parse error: syntax error, unexpected '[' in L:\home\test1.ru\quickhire\application\libraries\account\Authorization.php on line 79 

 if ( ! is_array($permission_keys))
        {
            $permission_keys = [$permission_keys];
        }

?????? What this means???

**Comment by AdwinTrave** [comment]
What version of PHP are you using?

**Comment by maridansoft** [comment]
5.3.13
