### ISSUE TITLE
application/views/template.php 15th line error and sigup error

### ISSUE THREAD

**Issue by Gnanalingam** [donjakobo/A3M#137]
application/views/template.php 15th line error and sigup error

nor respond create new account pleas help

**Comment by Gnanalingam** [comment]
application/views/template.php 15th line error and sigup error

not respond create new account pleas help

**Comment by Gnanalingam** [comment]
application/views/template.php 15th line error and sigup error

not respond create new account pleas help

**Comment by Gnanalingam** [comment]
application/views/template.php 15th line error.

not respond create new account btn  pleas help.
pleas fix this issue

**Comment by AdwinTrave** [comment]
Which version is this?

**Comment by Gnanalingam** [comment]
Thank you sir.
i am move to  Octobercms
