### ISSUE TITLE
Fatal error: Call to undefined function check_reset_password() after signing in

### ISSUE THREAD

**Issue by gavu** [donjakobo/A3M#145]
Hi,

while using/testing the ci3_beta, after signing in, I get the following error:

Fatal error: Call to undefined function check_reset_password() in ***/application/libraries/account/Authentication.php on line 203

Did I miss something?

Cheers,
Andrei

**Comment by StorytellerCZ** [comment]
No, I just forgot to merge the fix for this that I did in my branch. Fixed now in #146

**Comment by gavu** [comment]
Awesome! Thanks! I'll check it out later!
