### ISSUE TITLE
Facebook  Not working 

### ISSUE THREAD

**Issue by gelinger777** [donjakobo/A3M#148]
Seems the CONFIG key of storage is not created 

An uncaught Exception was encountered

Type: Hybrid_Exception

Message: Endpoint: Error while trying to init Hybrid_Auth: You cannot access this page directly.

Filename: /***/application/third_party/Hybrid/Endpoint.php

Line Number: 217

Backtrace:

When i do print_r($_SESSION) there I see

Array ( [HA::CONFIG] => Array ( [php_session_id] => s:40:"89afd49c545d5b3bd85b4717d2dfe4f20fa854e7"; [version] => s:5:"2.6.0"; ) )

So what to do?

**Comment by maridansoft** [comment]
Seems the problem is the sessions... Still couldnt resolve it. Any ideas?

**Comment by StorytellerCZ** [comment]
Should upgrade the version of HybridAuth as well.

**Comment by gelinger777** [comment]
hahaha :) 2 years back ticket... :) Have a nice day @StorytellerCZ

**Comment by StorytellerCZ** [comment]
Strange it came up yeasterday on my notifications as a recent thing. :thinking:
