### ISSUE TITLE
Google sign in error

### ISSUE THREAD

**Issue by KizaBre** [donjakobo/A3M#96]
Google has deprecated OpenID 2.0 and will shut it down after a migration period.
So google accounts that have google+ enabled can't log in/sign up.

**Comment by samuelsh** [comment]
@AdwinTrave Hi, looks like v2 still didn't have the fix for Google OpenId 2.0 expiration,  though there's a patch on https://github.com/hybridauth/hybridauth/issues/221
Are there plans to fix it in v2?
Thank You

**Comment by AdwinTrave** [comment]
Actually if you look on HybridAuth the issue still wasn't resolved. I'm looking into this right now, but my time is very limited so I don't know how far I'll get.

**Comment by samuelsh** [comment]
Thanks @AdwinTrave 
I really would like to help with this because lots of my site users are authenticated via google, so in april, they won't be able to login, what's pretty critical for me :)
How can I help to complete this fix?
Maybe we should look into  https://github.com/google/google-api-php-client as well?

Thanks

**Comment by AdwinTrave** [comment]
Hi @samuelsh 
If you want to help the best way for version 2 would be to look on HybridAuth and fix the problem there. For v1 feel free to go into the code and make any changes you think are necessary. I will be happy to merge any PR that fixes this issue anywhere where I have the right to do so. I think the Google library you mentioned is something that could be applied to A3M v1.

Thanks

**Comment by samuelsh** [comment]
Thanks @AdwinTrave .
I started to look into A3M v2 at https://github.com/donjakobo/A3M (hopefully it's a right repo :))
The strange thing that I didn't find any mention of HybridAuth library. Actually looks like all the authentication stuff done vs. Yadis openID.
```
grep -nr --color "openid2" .
./application/helpers/account/php-openid-php5.3/Auth/OpenID/Discover.php:262:                                       
'openid2.provider', 'openid2.local_id')
```
Can you please elaborate on this? Can be that I'm looking into the wrong A3M version?
Thanx

**Comment by AdwinTrave** [comment]
You have the right repository, but the wrong branch.
Look here: https://github.com/donjakobo/A3M/tree/ci3-beta

**Comment by samuelsh** [comment]
Thanks @AdwinTrave ,
Looking into that now.
One question, after enabling Google in account.php, I see "Google" icon on "Sign-in" page, but it takes me to non-existing page http://localhost/dogen/CodeIgniter/account/connect/Google.
How can I fix it?

Thanks

**Comment by AdwinTrave** [comment]
The link seems fine and it should be processed by `controllers/account/Connect.php`, what exactly is the error you get?

**Comment by samuelsh** [comment]
@AdwinTrave It's 404 "Page not found"

**Comment by samuelsh** [comment]
Ok this one fixed by modifying config.php:

$autoload['packages'] = array(APPPATH.'third_party/Hybrid');
...
$autoload['config'] = array("account/account.php");

But then failed on following:
Type: Hybrid_Exception

Message: Oophs. Error!

Filename: /home/dogen/htdocs/CodeIgniter/application/third_party/Hybrid/Endpoint.php

Line Number: 215

I guess it somehow fails to init:
Storage.php
210:	Hybrid_Auth::initialize( $storage->config( "CONFIG" ) );

**Comment by samuelsh** [comment]
@AdwinTrave 
Well looks like this is the problem:
Endpoint.php
// Check if Hybrid_Auth session already exist
				if ( ! $storage->config( "CONFIG" ) ) {

					throw new Hybrid_Exception( "You cannot access this page directly." );
				}

Type: Hybrid_Exception

Message: Oophs. Error! You cannot access this page directly.

Filename: /home/dogen/htdocs/CodeIgniter/application/third_party/Hybrid/Endpoint.php

Line Number: 216

Do you have a solution for that issue?

Thanks

**Comment by AdwinTrave** [comment]
There were recently some changes made to the endpoint, I'll pull in the changes and we'll see if that makes any difference.

**Comment by samuelsh** [comment]
Thanks @AdwinTrave ,
Please let me know when you pull in the changes

**Comment by samuelsh** [comment]
Hi @AdwinTrave 
I ugraded to newest, but there's still the same error:
Endpoint.php
// Check if Hybrid_Auth session already exist
if ( ! $storage->config( "CONFIG" ) ) {
                throw new Hybrid_Exception( "You cannot access this page directly." );
            }
...
Now when looking into Storage.php::config(), it looks like we'll always get exceptions, if "config" exists:
 	public function config($key, $value = null)
	{
		$key = strtolower( $key );

		if( $value ){
            $_SESSION["HA::CONFIG"][$key] = serialize( $value );
		}
		elseif( isset( $_SESSION["HA::CONFIG"][$key] ) ){
			return unserialize( $_SESSION["HA::CONFIG"][$key] );
		}
return NULL;
}

I can't understand the logic behind, maybe it supposed to pevents initialise Hybrid session twice?
And if so, how can it be avoided?

Thanks

**Comment by samuelsh** [comment]
Here's hybridauth log. I didn't find any problem here:
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Enter Hybrid_Auth::initialize() --- DEBUG SOM
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Auth::initialize(). PHP version: 5.4.39-0+deb7u2
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Auth::initialize(). Hybrid_Auth version: 2.4.0
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Auth::initialize(). Hybrid_Auth called from: http://archivesupport.co
m/account/connect/Google
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- PHP session.name diff from default PHPSESSID. http://php.net/manual/en/sessi
on.configuration.php#ini.session.name.
DEBUG -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Auth initialize. dump used config:  -- a:8:{s:8:"base_url";s:45:"htt
p://archivesupport.com/account/connect_end";s:9:"providers";a:9:{s:6:"OpenID";a:1:{s:7:"enabled";b:1;}s:5:"Yahoo";a:2:{s:7:"en
abled";b:0;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:3:"AOL";a:1:{s:7:"enabled";b:1;}s:6:"Google";a:3:{s:7:"ena
bled";b:1;s:4:"keys";a:2:{s:2:"id";s:71:"16250304081-2s4dsb6cd7fmordg7iea6dla51ujgd8g.apps.googleusercontent.com";s:6:"secret"
;s:24:"99pGnb2Buefsbr96p0u--nZO";}s:2:"hd";s:18:"archivesupport.com";}s:8:"Facebook";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:
2:"id";s:0:"";s:6:"secret";s:0:"";}}s:7:"Twitter";a:2:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";
}}s:4:"Live";a:2:{s:7:"enabled";b:0;s:4:"keys";a:2:{s:2:"id";s:0:"";s:6:"secret";s:0:"";}}s:8:"LinkedIn";a:2:{s:7:"enabled";b:
1;s:4:"keys";a:2:{s:3:"key";s:0:"";s:6:"secret";s:0:"";}}s:10:"Foursquare";a:2:{s:7:"enabled";b:0;s:4:"keys";a:2:{s:2:"id";s:0
:"";s:6:"secret";s:0:"";}}}s:10:"debug_mode";b:1;s:10:"debug_file";s:63:"/home/dogen/htdocs/CodeIgniter/application//logs/hybr
idauth.log";s:9:"path_base";s:62:"/home/dogen/htdocs/CodeIgniter/application/third_party/Hybrid/";s:14:"path_libraries";s:73:"
/home/dogen/htdocs/CodeIgniter/application/third_party/Hybrid/thirdparty/";s:14:"path_resources";s:72:"/home/dogen/htdocs/Code
Igniter/application/third_party/Hybrid/resources/";s:14:"path_providers";s:72:"/home/dogen/htdocs/CodeIgniter/application/thir
d_party/Hybrid/Providers/";}
DEBUG -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Auth initialize. dump current session:  -- a:3:{s:36:"hauth_session.
google.hauth_return_to";s:56:"s:48:"http://archivesupport.com/account/connect/Google";";s:35:"hauth_session.google.hauth_endpo
int";s:71:"s:63:"http://archivesupport.com/account/connect_end?hauth.done=Google";";s:39:"hauth_session.google.id_provider_par
ams";s:385:"a:5:{s:15:"hauth_return_to";s:48:"http://archivesupport.com/account/connect/Google";s:11:"hauth_token";s:40:"c309e
d08cc0a99916d7e3124dcb68e9bed8a0ad8";s:10:"hauth_time";i:1427768545;s:11:"login_start";s:86:"http://archivesupport.com/account
/connect_end?hauth.start=Google&hauth.time=1427768545";s:10:"login_done";s:63:"http://archivesupport.com/account/connect_end?h
auth.done=Google";}";}
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Auth initialize: check if any error is stored on the endpoint...
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Auth initialize: no error found. initialization succeed.
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Enter Hybrid_Auth::authenticate( Google )
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Auth::authenticate( Google ), User not connected to the provider. Try to authenticate..
DEBUG -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Enter Hybrid_Auth::setup( Google ) -- 
DEBUG -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Auth::setup( Google ), no params given. Trying to get the stored for this provider. -- Array
(
    [hauth_return_to] => http://archivesupport.com/account/connect/Google
    [hauth_token] => c309ed08cc0a99916d7e3124dcb68e9bed8a0ad8
    [hauth_time] => 1427768545
    [login_start] => http://archivesupport.com/account/connect_end?hauth.start=Google&hauth.time=1427768545
    [login_done] => http://archivesupport.com/account/connect_end?hauth.done=Google
)

INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Enter Hybrid_Provider_Adapter::factory( Google )
DEBUG -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Provider_Model::__construct( Google ) initialized. dump current adapter instance:  -- O:23:"Hybrid_Providers_Google":7:{s:5:"scope";s:132:"https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read https://www.google.com/m8/feeds/";s:10:"providerId";s:6:"Google";s:6:"config";a:3:{s:7:"enabled";b:1;s:4:"keys";a:2:{s:2:"id";s:71:"16250304081-2s4dsb6cd7fmordg7iea6dla51ujgd8g.apps.googleusercontent.com";s:6:"secret";s:24:"99pGnb2Buefsbr96p0u--nZO";}s:2:"hd";s:18:"archivesupport.com";}s:6:"params";a:5:{s:15:"hauth_return_to";s:48:"http://archivesupport.com/account/connect/Google";s:11:"hauth_token";s:40:"c309ed08cc0a99916d7e3124dcb68e9bed8a0ad8";s:10:"hauth_time";i:1427768545;s:11:"login_start";s:86:"http://archivesupport.com/account/connect_end?hauth.start=Google&hauth.time=1427768545";s:10:"login_done";s:63:"http://archivesupport.com/account/connect_end?hauth.done=Google";}s:8:"endpoint";s:63:"http://archivesupport.com/account/connect_end?hauth.done=Google";s:4:"user";O:11:"Hybrid_User":3:{s:10:"providerId";s:6:"Google";s:9:"timestamp";i:1427769706;s:7:"profile";O:19:"Hybrid_User_Profile":22:{s:10:"identifier";N;s:10:"webSiteURL";N;s:10:"profileURL";N;s:8:"photoURL";N;s:11:"displayName";N;s:11:"description";N;s:9:"firstName";N;s:8:"lastName";N;s:6:"gender";N;s:8:"language";N;s:3:"age";N;s:8:"birthDay";N;s:10:"birthMonth";N;s:9:"birthYear";N;s:5:"email";N;s:13:"emailVerified";N;s:5:"phone";N;s:7:"address";N;s:7:"country";N;s:6:"region";N;s:4:"city";N;s:3:"zip";N;}}s:3:"api";O:12:"OAuth2Client":23:{s:12:"api_base_url";s:0:"";s:13:"authorize_url";s:41:"https://accounts.google.com/o/oauth2/auth";s:9:"token_url";s:42:"https://accounts.google.com/o/oauth2/token";s:14:"token_info_url";s:46:"https://www.googleapis.com/oauth2/v2/tokeninfo";s:9:"client_id";s:71:"16250304081-2s4dsb6cd7fmordg7iea6dla51ujgd8g.apps.googleusercontent.com";s:13:"client_secret";s:24:"99pGnb2Buefsbr96p0u--nZO";s:12:"redirect_uri";s:63:"http://archivesupport.com/account/connect_end?hauth.done=Google";s:12:"access_token";s:0:"";s:13:"refresh_token";s:0:"";s:23:"access_token_expires_in";s:0:"";s:23:"access_token_expires_at";s:0:"";s:15:"sign_token_name";s:12:"access_token";s:11:"decode_json";b:1;s:13:"curl_time_out";i:30;s:21:"curl_connect_time_out";i:30;s:19:"curl_ssl_verifypeer";b:0;s:19:"curl_ssl_verifyhost";b:0;s:11:"curl_header";a:1:{i:0;s:21:"Authorization: OAuth ";}s:14:"curl_useragent";s:77:"OAuth/2 Simple PHP Client v0.1; HybridAuth http://hybridauth.sourceforge.net/";s:24:"curl_authenticate_method";s:4:"POST";s:10:"curl_proxy";N;s:9:"http_code";s:0:"";s:9:"http_info";s:0:"";}}
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Enter Hybrid_Provider_Adapter::login( Google ) 
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Enter [Google]::logout()
DEBUG -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Hybrid_Provider_Adapter::login( Google ), redirect the user to login_start URL. -- 
INFO -- 127.0.0.1 -- 2015-03-31T05:41:46+03:00 -- Enter Hybrid_Auth::redirect( http://archivesupport.com/account/connect_end?hauth.start=Google&hauth.time=1427769706, PHP )

**Comment by samuelsh** [comment]
Hi @AdwinTrave ,
After some debugging looks loke the reason is, that after redirection I'm somehow loosing my $_SESSION with all the config data.
$_SESSION["HA::CONFIG"][$key] is empty after redirection to: 
http://archivesupport.com/account/connect_end?hauth.start=Google&hauth.time=1428547607

Any thoughts?

Thanks

**Comment by AdwinTrave** [comment]
There seems to be some issue with Google in general, there are some efforts underway at HybridAuth to fix it. I'll let you know once I merge some improvements.

**Comment by samuelsh** [comment]
Thanks @AdwinTrave 
Will wait for updates.
Meanwhile I did some changes in v1 google_connect controller, to work with 'https://github.com/google/google-api-php-client" library.
It actually fixed the "openid2 miggration" issue. 
Would you like to see the code and do some code review, so we could push 'em to the master later?

Thanks

**Comment by AdwinTrave** [comment]
@samuelsh That sounds great! Submit a pull request. That is a best way to review code.
